Repository beryxz/appunti-analisi-2, pull requests merged in 2024-10, with the labels that each got.

#2 Fix #1
  argomenti/equazioni-differenziali/edo-lineari-1-ordine.tex
Labels: problem

#10 feat(spazio-metrico): nuove immagini
  argomenti/calcolo-infinitesimale/spazio-metrico.tex
  images/distanza-euclidea-esempio.png
  images/distanza-taxicab-esempio.png
  images/insiemi-aperti-esempio-1.png
  images/insiemi-aperti-esempio-2.png
  images/insiemi-aperti-esempio-3.png
Labels: area/immagini

#12 Fix #11
  argomenti/equazioni-differenziali/edo-lineari-2-ordine.tex
Labels: area/esempi
